"""Model for LLM-generated topics without DB match."""

from dataclasses import dataclass


@dataclass
class GeneratedTopic:
    """Represents a topic generated by LLM that has no DB match."""

    title: str
    source: str = "generated"  # Distinguish from DB topics

    def __repr__(self) -> str:
        return f"<GeneratedTopic(title='{self.title}')>"
