"""Internal domain models for GEO schema audit."""

from dataclasses import dataclass, field
from typing import Literal

SchemaFormat = Literal["json-ld", "microdata", "rdfa"]


@dataclass
class DetectedSchema:
    """A single structured data block found in HTML."""

    format: SchemaFormat
    schema_type: str
    raw_content: str
    properties: dict


@dataclass
class ExtractionResult:
    """Result of Step 1: all structured data found in a page."""

    schemas: list[DetectedSchema] = field(default_factory=list)
    total_blocks: int = 0
    formats_found: list[SchemaFormat] = field(default_factory=list)
    schema_types_found: list[str] = field(default_factory=list)


@dataclass
class ValidationIssue:
    """A single validation problem found in a schema."""

    schema_type: str
    severity: Literal["error", "warning"]
    field: str | None
    message: str


@dataclass
class ValidationResult:
    """Result of Step 2: validation of all detected schemas."""

    issues: list[ValidationIssue] = field(default_factory=list)
    valid_count: int = 0
    invalid_count: int = 0


@dataclass
class RichResultGap:
    """A missing or incomplete rich result opportunity."""

    schema_type: str
    status: Literal["missing", "incomplete"]
    missing_required: list[str] = field(default_factory=list)
    missing_recommended: list[str] = field(default_factory=list)


@dataclass
class RichResultCheckResult:
    """Result of Step 3: rich result eligibility."""

    eligible: list[str] = field(default_factory=list)
    gaps: list[RichResultGap] = field(default_factory=list)


@dataclass
class GeoSignal:
    """Assessment of a single GEO-critical signal."""

    name: str
    present: bool
    completeness: float  # 0.0 to 1.0
    details: str


@dataclass
class SameAsLink:
    """A single sameAs entity link."""

    platform: str
    linked: bool
    url: str | None = None


@dataclass
class GeoReadinessResult:
    """Result of Step 4: GEO-critical schema evaluation."""

    signals: list[GeoSignal] = field(default_factory=list)
    same_as_links: list[SameAsLink] = field(default_factory=list)
    overall_readiness: float = 0.0


@dataclass
class DeprecatedSchemaWarning:
    """A deprecated or removed schema found on the page."""

    schema_type: str
    status: Literal["removed", "restricted", "deprecated"]
    message: str


@dataclass
class JsRenderingWarning:
    """Warning about JS framework detection."""

    framework: str
    confidence: Literal["high", "medium", "low"]
    message: str


@dataclass
class GeneratedTemplate:
    """A recommended JSON-LD template generated by OpenAI."""

    schema_type: str
    json_ld: str
    rationale: str


@dataclass
class ScoreBreakdown:
    """Individual component of the audit score."""

    component: str
    max_points: float
    earned_points: float


@dataclass
class AuditScore:
    """Result of Step 8: final weighted score."""

    total: float
    rating: Literal["Critical", "Poor", "Fair", "Good", "Excellent"]
    breakdown: list[ScoreBreakdown] = field(default_factory=list)


@dataclass
class GeoAuditReport:
    """Complete audit report assembled by the orchestrator."""

    url: str
    extraction: ExtractionResult
    validation: ValidationResult
    rich_results: RichResultCheckResult
    geo_readiness: GeoReadinessResult
    deprecated_schemas: list[DeprecatedSchemaWarning]
    js_rendering_warnings: list[JsRenderingWarning]
    recommended_templates: list[GeneratedTemplate]
    score: AuditScore
