"""ISO country code to location name mapping for DataForSEO API."""

from typing import Optional

# Mapping of ISO country codes to location names
ISO_TO_LOCATION_NAME = {
    "UA": "Ukraine",
    "AL": "Albania",
    "DZ": "Algeria",
    "AO": "Angola",
    "AZ": "Azerbaijan",
    "AR": "Argentina",
    "AU": "Australia",
    "AT": "Austria",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "AM": "Armenia",
    "BE": "Belgium",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "MM": "Myanmar (Burma)",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "LK": "Sri Lanka",
    "CL": "Chile",
    "TW": "Taiwan",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "HR": "Croatia",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DK": "Denmark",
    "EC": "Ecuador",
    "SV": "El Salvador",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GH": "Ghana",
    "GR": "Greece",
    "GT": "Guatemala",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IN": "India",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "CI": "Cote d'Ivoire",
    "JP": "Japan",
    "KZ": "Kazakhstan",
    "JO": "Jordan",
    "KE": "Kenya",
    "KR": "South Korea",
    "LV": "Latvia",
    "LT": "Lithuania",
    "MY": "Malaysia",
    "MT": "Malta",
    "MX": "Mexico",
    "MC": "Monaco",
    "MD": "Moldova",
    "MA": "Morocco",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NG": "Nigeria",
    "NO": "Norway",
    "PK": "Pakistan",
    "PA": "Panama",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SG": "Singapore",
    "SK": "Slovakia",
    "VN": "Vietnam",
    "SI": "Slovenia",
    "ZA": "South Africa",
    "ES": "Spain",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TH": "Thailand",
    "AE": "United Arab Emirates",
    "TN": "Tunisia",
    "TR": "Turkiye",
    "MK": "North Macedonia",
    "EG": "Egypt",
    "GB": "United Kingdom",
    "US": "United States",
    "BF": "Burkina Faso",
    "UY": "Uruguay",
    "VE": "Venezuela",
}


def get_location_name(iso_code: str) -> Optional[str]:
    """
    Get location name from ISO country code.

    Args:
        iso_code: ISO country code (e.g., 'US', 'GB', 'UA')

    Returns:
        Location name if found, None otherwise
    """
    return ISO_TO_LOCATION_NAME.get(iso_code.upper())
