"""Router for prompts endpoints."""

from typing import List

from fastapi import APIRouter, Depends, HTTPException, Query

from src.auth.deps import CurrentUser
from src.config.settings import settings
from src.geography.services import CountryService, get_country_service
from src.prompts.services import (
    PromptService,
    get_prompt_service,
)
from src.businessdomain.services import (
    CompanyMetaInfoService,
    get_company_meta_info_service,
)
from src.businessdomain.models import (
    CompanyMetaInfoResponse,
    DBTopicResponse,
    GeneratedTopicResponse,
    TopicsResponse,
)
from src.prompts.models import (
    PromptResponse,
    PromptsListResponse,
    SimilarPromptResponse,
    SimilarPromptsResponse,
    TopicPromptsResponse,
)
from src.utils.url_validator import extract_domain, validate_url

router = APIRouter(prefix="/prompts/api/v1", tags=["prompts"])


@router.get("/meta-info", response_model=CompanyMetaInfoResponse)
async def get_company_meta_info(
    current_user: CurrentUser,
    company_url: str = Query(
        ..., description="Company website URL (e.g., 'moyo.ua', 'https://example.com')"
    ),
    iso_country_code: str = Query(..., description="ISO 3166-1 alpha-2 country code (e.g., 'UA', 'US')"),
    meta_service: CompanyMetaInfoService = Depends(get_company_meta_info_service),
    country_service: CountryService = Depends(get_country_service),
):
    """
    Get company metadata including business domain, topics, and brand variations.

    Uses a 2-call approach to OpenAI:
    1. Detect business domain and language-specific brand variations
    2. Generate domain-specific topics and match with DB topics

    Topics are returned in two categories:
    - matched_topics: Topics found in database (have ID, description, can be referenced)
    - unmatched_topics: Topics generated by LLM (title only, no DB match)

    Args:
        company_url: Company website URL
        iso_country_code: ISO country code to determine languages for brand variations

    Returns:
        CompanyMetaInfoResponse with:
        - business_domain: e-comm or null if not supported
        - topics: Object with matched_topics (DB) and unmatched_topics (generated)
        - brand_variations: List of brand name variations in country-specific languages

    Raises:
        HTTPException 400: Invalid URL or ISO code
        HTTPException 500: Service errors

    Example:
        GET /prompts/api/v1/meta-info?company_url=moyo.ua&iso_country_code=UA

        Response for e-commerce:
        {
            "business_domain": "e-comm",
            "topics": {
                "matched_topics": [
                    {
                        "id": 1,
                        "title": "Смартфони і телефони",
                        "description": "Пошук і покупка телефонів і смартфонів в інтернеті",
                        "business_domain_id": 1,
                        "country_id": 1
                    }
                ],
                "unmatched_topics": [
                    {"title": "Телевізори", "source": "generated"}
                ]
            },
            "brand_variations": ["moyo", "мойо", "MOYO", "Мойо"]
        }

        Response for non-supported:
        {
            "business_domain": null,
            "topics": {"matched_topics": [], "unmatched_topics": []},
            "brand_variations": ["brandname", "БрендНейм"]
        }
    """
    try:
        # Validate URL and extract domain
        await validate_url(company_url)
        domain = extract_domain(company_url)

        # Validate country code
        country = await country_service.get_by_iso_code(iso_country_code)
        if not country:
            raise HTTPException(
                status_code=400, detail=f"Invalid ISO country code: {iso_country_code}"
            )

        # Get company metadata (pass Country object to avoid redundant query)
        meta_info = await meta_service.get_meta_info(domain, country)

        # Convert TopicMatchResult to API response format
        topics_response = TopicsResponse(
            matched_topics=[
                DBTopicResponse.model_validate(topic)
                for topic in meta_info.topics.matched_topics
            ],
            unmatched_topics=[
                GeneratedTopicResponse(
                    title=topic.title,
                    source=topic.source
                )
                for topic in meta_info.topics.unmatched_topics
            ]
        )

        return CompanyMetaInfoResponse(
            business_domain=meta_info.business_domain.name if meta_info.business_domain else None,
            topics=topics_response,
            brand_variations=meta_info.brand_variations,
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Failed to get company meta info: {str(e)}"
        )


@router.get("/prompts", response_model=PromptsListResponse)
async def get_prompts(
    current_user: CurrentUser,
    topic_ids: List[int] = Query(..., description="List of topic IDs to retrieve prompts for"),
    prompt_service: PromptService = Depends(get_prompt_service),
):
    """
    Get prompts from database for given topic IDs.

    Retrieves pre-seeded prompts for the specified topics.
    Prompts are grouped by topic_id for easy consumption.

    Args:
        topic_ids: List of topic IDs (from /meta-info endpoint)

    Returns:
        PromptsListResponse with prompts grouped by topic

    Raises:
        HTTPException 400: Empty topic_ids list
        HTTPException 404: No prompts found for given topic IDs
        HTTPException 500: Database errors

    Example:
        GET /prompts/api/v1/prompts?topic_ids=1&topic_ids=2

        Response:
        {
            "topics": [
                {
                    "topic_id": 1,
                    "prompts": [
                        {
                            "id": 1,
                            "prompt_text": "Купити смартфон в Україні з швидкою доставкою"
                        },
                        ...
                    ]
                },
                {
                    "topic_id": 2,
                    "prompts": [...]
                }
            ]
        }
    """
    try:
        # Validate topic_ids
        if not topic_ids:
            raise HTTPException(
                status_code=400, detail="At least one topic_id must be provided"
            )

        # Fetch prompts from database
        prompts = await prompt_service.get_by_topic_ids(topic_ids)

        if not prompts:
            raise HTTPException(
                status_code=404,
                detail=f"No prompts found for topic IDs: {topic_ids}"
            )

        # Group prompts by topic_id
        topics_map = {}
        for prompt in prompts:
            if prompt.topic_id not in topics_map:
                topics_map[prompt.topic_id] = []

            topics_map[prompt.topic_id].append(
                PromptResponse(
                    id=prompt.id,
                    prompt_text=prompt.prompt_text,
                )
            )

        # Build response
        topics_list = [
            TopicPromptsResponse(topic_id=topic_id, prompts=prompts_list)
            for topic_id, prompts_list in sorted(topics_map.items())
        ]

        return PromptsListResponse(topics=topics_list)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Failed to retrieve prompts: {str(e)}"
        )


@router.get("/similar", response_model=SimilarPromptsResponse)
async def find_similar_prompts(
    current_user: CurrentUser,
    text: str = Query(
        ...,
        min_length=1,
        max_length=1000,
        description="Input text to find similar prompts for",
    ),
    k: int = Query(
        10,
        ge=1,
        le=settings.similar_prompts_max_k,
        description=f"Maximum number of results (max {settings.similar_prompts_max_k})",
    ),
    min_similarity: float = Query(
        0.55,
        gt=settings.similar_prompts_min_similarity_threshold,
        le=1.0,
        description=f"Minimum similarity threshold (must be > {settings.similar_prompts_min_similarity_threshold})",
    ),
    prompt_service: PromptService = Depends(get_prompt_service),
):
    """
    Find similar prompts by semantic similarity.

    Uses pgvector cosine similarity with HNSW index for fast approximate
    nearest neighbor search. Returns prompts sorted by similarity (highest first).

    Designed for autocomplete: as user types, call this endpoint to suggest
    relevant existing prompts from the database.

    Args:
        text: Input text to find similar prompts for
        k: Maximum number of results to return (default 10, max 100)
        min_similarity: Minimum cosine similarity threshold (default 0.75, must be > 0.7)

    Returns:
        SimilarPromptsResponse with:
        - query_text: The input text that was searched
        - prompts: List of similar prompts with id, prompt_text, and similarity score
        - total_found: Number of prompts returned

    Example:
        GET /prompts/api/v1/similar?text=купити смартфон&k=5&min_similarity=0.8

        Response:
        {
            "query_text": "купити смартфон",
            "prompts": [
                {
                    "id": 42,
                    "prompt_text": "Купити смартфон в Україні з швидкою доставкою",
                    "similarity": 0.92
                },
                ...
            ],
            "total_found": 5
        }
    """
    try:
        results = await prompt_service.find_similar(
            query_text=text,
            limit=k,
            min_similarity=min_similarity,
        )

        prompts = [
            SimilarPromptResponse(
                id=result.id,
                prompt_text=result.prompt_text,
                similarity=round(result.similarity, 4),
            )
            for result in results
        ]

        return SimilarPromptsResponse(
            query_text=text,
            prompts=prompts,
            total_found=len(prompts),
        )

    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Failed to find similar prompts: {str(e)}"
        )
